дз №7
mishhgun01/go2022 pull request #15
Opened 2022-04-11 23:42 UTC by mishhgun01

2022-04-12 12:39 UTC, DmitriyVTitov requested changes
не принято

2022-04-12 12:39 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +	}
чем эти два примера отличаются?

2022-04-12 12:39 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +		{"test4", []string{"3", "1", "2"}, []string{"1", "2", "3"}},
эти примеры также очень похожи; где пустой массив, nil?

2022-04-12 12:39 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +//результат для данного алгоритма - 3497976445 ns/op при сложности O(n^2)
1. где многократное выполнение операции?
2. почему вдруг разная сложность сортировки?

2022-04-12 12:42 UTC, mishhgun01 commented on hw7/sort_test.go
> +	}
> чем эти два примера отличаются?

отличаются повторением элементов

2022-04-12 12:43 UTC, mishhgun01 commented on hw7/sort_test.go
> +//результат для данного алгоритма - 3497976445 ns/op при сложности O(n^2)
> 1. где многократное выполнение операции?
> 2. почему вдруг разная сложность сортировки?

из-за квадратной сложности алгоритма рандомайзера строк

2022-04-12 12:45 UTC, mishhgun01 commented on hw7/sort_test.go
> +		{"test4", []string{"3", "1", "2"}, []string{"1", "2", "3"}},
> эти примеры также очень похожи; где пустой массив, nil?

Почему похожи? Я проверяю как сортируются буквы, слова, одинаковые буквы в разных количествах и цифры в строковом представлении

2022-04-22 08:22 UTC, DmitriyVTitov requested changes
Не принято.

2022-04-22 08:22 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +// 3 - слайс с повторяющимися элементами и нестандартной записью числа
между этими примерами существенных отличий нет, на мой взгляд

2022-04-22 08:22 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +		}
где заканчивается один пример и начинается второй?
зачем вообще в простом тесте несколько примеров? для этого нужно использовать табличный тест

2022-04-22 08:22 UTC, DmitriyVTitov commented on hw7/sort_test.go
> +		{"test4", []string{"3", "1", "2"}, []string{"1", "2", "3"}},                                   //как сортируются цифры в строковом виде
1. нужно явно писать имена полей в литералах структур, в таком виде невозможно понять где что
2. примеры ничем не отличаются: то, что написано в комментарии - это не различия совершенно
3. комментарии вот так сбоку не пишутся, я добавлю ещё одну строку и комментарий разъедется

2022-05-17 15:45 UTC, closed without merging