Hw15
mishhgun01/go2022 pull request #23
Opened 2022-05-17 17:00 UTC by mishhgun01

Разработать схему БД для хранения данных о фильмах.
![Снимок экрана от 2022-05-25 21-05-19](https://user-images.githubusercontent.com/67867944/170336460-33d2eb65-4df1-417f-8762-b1a20ec6fee6.png)
![Снимок экрана от 2022-05-25 21-06-44](https://user-images.githubusercontent.com/67867944/170336490-806c136b-cf99-4b44-8dae-05b20227cc83.png)

2022-05-19 08:33 UTC, mishhgun01 commented
ОК

2022-05-25 12:08 UTC, DmitriyVTitov requested changes
Схема вообще не работает!
Уже не первое задание, которое не работает вообще. Надо менять отношение.

2022-05-25 12:08 UTC, DmitriyVTitov commented on hw15/schema.sql
> +);
я ожидал увидеть тут ENUM, но можно и так

2022-05-27 16:20 UTC, DmitriyVTitov approved these changes
OK
С Тичбейза куда-то пропала задача №3 по составлению запросов, но вижу что-то в описании PR.

2022-05-27 16:27 UTC, merged