hw16
mishhgun01/go2022 pull request #24
Opened 2022-05-18 15:45 UTC by mishhgun01

Разработать пакет для работы с БД сайта о фильмах. Схему БД взять из предыдущего задания.

2022-05-18 15:47 UTC, mishhgun01 commented
OK

2022-05-29 01:50 UTC, DmitriyVTitov requested changes
В коде ошибки.
Михаил, в твоих ответах на ДЗ постоянно видна небрежность. Поскольку мы работаем над одним проектом, то тем более важно пересмотреть свои методы.
Да, не очень хочется всё проверять, но надо. Надо сделать БД, написать тесты, проверить.
Если что-то не даётся - обращайся ко мне или к Володе Грибанову. Он, к слову, тоже учился на моём курсе и сейчас пишет очень качественно.

2022-05-29 01:50 UTC, DmitriyVTitov commented on hw16/pkg/models/models.go
> +}
Не хватает только `view`.
Вообще в Go подход MVC не принят.

2022-05-29 01:50 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +	ORDER BY id`,
```
При получении массива фильмов должна быть реализована возможность указать ID студии для фильтра по студии. Если ID не указан (== 0), то возвращать все фильмы.
```
Что-то не похоже.

2022-05-29 01:50 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +			item.Year,
а тут чего вдруг не указатель?

2022-05-31 12:11 UTC, DmitriyVTitov requested changes
Условия задания опять не выполнены.

2022-05-31 12:11 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +	"golang.org/x/net/context"
As of Go 1.7 this package is available in the standard library under the name context. https://golang.org/pkg/context.
https://pkg.go.dev/golang.org/x/net/context

Т.е. просто `"context"`

2022-05-31 12:11 UTC, DmitriyVTitov commented on hw16/pkg/models/structures.go
> +package pkg
`package pkg` ?
такого пакета быть не должно

2022-05-31 12:11 UTC, DmitriyVTitov commented on hw16/pkg/models/structures.go
> +package pkg
тут же каталог `models` - имя каталога и пакета должны совпадать

2022-05-31 12:11 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +	}
```
При получении массива фильмов должна быть реализована возможность указать ID студии для фильтра по студии. Если ID не указан (== 0), то возвращать все фильмы.
```

почему-то опять массив и проверка его длины

2022-06-09 12:10 UTC, DmitriyVTitov requested changes
Опять небрежно. Код элементарно не рабочий.

2022-06-09 12:10 UTC, DmitriyVTitov commented on hw16/pkg/models/interface.go
> +}
как связан интерфейс с моделями?
почему он в этом пакете?

2022-06-09 12:10 UTC, DmitriyVTitov commented on hw16/pkg/models/interface.go
> +}
Хотя это и не важно. Интерфейс всё равно никем не выполняется.

2022-06-09 12:12 UTC, mishhgun01 commented on hw16/pkg/models/interface.go
> +}
как не выполняется то? он выполняется структурой Storage из пакета pgsql. интерфейс сделан для возможности дальнейшего расширения кода на другие хранилища.

2022-06-20 07:47 UTC, DmitriyVTitov approved these changes
Теперь отлично.

2022-06-20 07:47 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +func (s *Storage) Films(req models.Request) ([]models.Film, error) {
лучше передавать id студии, сигнатура будет понятнее

2022-06-20 07:47 UTC, DmitriyVTitov commented on hw16/pkg/pgsql/pgx.go
> +	return nil
это можно объединить: `return err`

2023-03-08 17:17 UTC, merged