Hw18
mishhgun01/go2022 pull request #27
Opened 2022-05-30 12:02 UTC by mishhgun01

Разработать микросервис хранения коротких гиперссылок.

Микросервис должен предоставлять HTTP-API со следующими методами:

1. добавление ссылки в БД – метод принимает ссылку, добавляет её в хранилище и возвращает короткую ссылку.

2. Получение оригинальной ссылки: метод принимает на вход короткую ссылку и возвращает оригинальную.

2022-05-30 12:02 UTC, mishhgun01 commented
OK

2022-06-06 14:33 UTC, DmitriyVTitov requested changes

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/cmd/links/links.go
> +}
сокращатель ссылок работает не так
например, https://bit.ly/3x6t2nj 
https://bitly.com/

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/api/api.go
> +const addr = "0.0.0.0:8080"
адрес не должен быть жёстко указан в пакете
вот скачал я этот пакет и как мне запустить API на другом адресе?

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/queue/queue.go
> +}
не понимаю идеи

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/queue/queue.go
> +}
очередь - это средство интеграции, а не БД
конкретно в этом задании она вообще не упоминается

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/links/links.go
> +	db.links = append(db.links, link)
ещё бы не помешала проверка на уникальность, но ОК

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/api/handlers.go
> +	short := api.s.NewLink(link)
сокращатель ссылок не принимает всякие параметры запроса - ссылка получается уже совсем не короткая
пример я приводил выше

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/api/api.go
> +}
пути очень длинные

2022-06-06 14:33 UTC, DmitriyVTitov commented on hw18/links-service/pkg/api/api.go
> +}
запуск http-сервера не входит в задачу API

2022-06-12 09:43 UTC, DmitriyVTitov requested changes
Не понимаю, где сам микросервис? В смысле сама программа?
Для запуска программы на Go в ней должна быть функция `main()`.

2022-06-20 07:54 UTC, DmitriyVTitov approved these changes
ОК

2022-06-20 07:54 UTC, DmitriyVTitov commented on hw18/links-service/cmd/main.go
> +}
Это что-то странное.
Смысл "сокращателя ссылок" в том, что при переходе по короткой ссылке он перенаправляет на длинную. То есть короткая должна вести на него, то есть у него должен быть свой домен.
Например, я купил домен `short.ru`, тогда я могу для "https://github.com/mishhgun01/go2022/pull/28/files" вернуть ссылку `hhtps://short.ru/AcvRty` и при переходе по короткой ссылке делать редирект на длинную.

2022-06-20 07:54 UTC, DmitriyVTitov commented on hw18/links-service/pkg/links/links.go
> +}
Здесь также требуется использовать мьютекс и это очень важно! В мьютексе нет магии, сам он ничего не защищает.
Здесь возможно одновременное чтение и запись в массив.

2022-06-20 07:54 UTC, DmitriyVTitov commented on hw18/links-service/pkg/links/links.go
> +}
не вижу чтобы тут формировалось какое-то случайное слово

2023-03-08 17:36 UTC, merged