дз 3
mishhgun01/go2022 pull request #9
Opened 2022-04-07 12:03 UTC by mishhgun01

2022-04-08 19:06 UTC, DmitriyVTitov requested changes
Pull Request должен быть полностью зелёным. Буквально.

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/cmd/Search.go
> +package cmd
в каталоге `cmd` должны располагаться исполняемые пакеты, т.е. пакеты `main`
пакет `cmd` - что-то странное

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +	scanOrg, err := scanner.Scan(urlGolangOrg, depthVar)
а здесь что с ошибкой? есть и ладно?

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +	scanOrg, err := scanner.Scan(urlGolangOrg, depthVar)
как считаешь, у Яндекса тоже в коде каждый сайт жёстко вбит?
нет, так не пойдёт

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/pkg/index/index.go
>  type Interface interface {
почему больше ничего не попало в PR?

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +	}
интересный подход, то есть не результаты поиска ищутся в индексе, а для каждого документа ищется его номер в результатах поиска
очень необычно

2022-04-08 19:06 UTC, DmitriyVTitov commented on hw3/pkg/crawler/spider/spider.go
> -	"go2022/pkg/crawler"
опять странные изменения

2022-04-21 21:27 UTC, mishhgun01 commented on hw3/cmd/main/main.go
> +	}
вот этого как раз и не понимаю - а как правильно?

2022-04-22 08:18 UTC, DmitriyVTitov requested changes
Много ошибок. Надо проверять собственный код.
В списке на проверку много ДЗ, лучше сосредоточиться на одном и сделать его качественно.

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +		}
если ошибка была, то результат невалидный и обрабатывать его нельзя
если результат представляет из себя указатель, то в случае ошибки будет возвращён nil и при обращении к нему будет паника

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +		}
то есть ВСЕГДА нужно сначала проверять ошибку

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +			log.Fatal(err)
log.Fatal() - крайнее средство и не должен использоваться почти нигде
что такого тут произошло? что, Яндекс роняет всю систему если не удалось просканировать один сайт?

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +	sort.Ints(idxArr)               //sorting
комментарии так не пишутся

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/pkg/Search/Search.go
> +package Search
есть в стандартной библиотеке хоть один пакет с большой буквы?

2022-04-22 08:18 UTC, DmitriyVTitov commented on hw3/pkg/Search/Search.go
> +	return index
не нашли и вернули первый элемент?
чему равен index, если ничего не найдено?

2022-04-22 08:25 UTC, mishhgun01 commented on hw3/pkg/Search/Search.go
> +	return index
равен -1

2022-04-22 08:25 UTC, mishhgun01 commented on hw3/pkg/Search/Search.go
> +	return index
> не нашли и вернули первый элемент?
> чему равен index, если ничего не найдено?

и в main я проверяю на key!=-1

2022-04-27 14:38 UTC, DmitriyVTitov requested changes
Видимо я не нажал кнопку на тичбейз.

2022-04-27 14:38 UTC, DmitriyVTitov commented on hw3/pkg/Search/Search.go
> +	return index
почему -1?
var index int - тут он = 0
дальше -1 только если вышел за границы массива

вот массив: 0, 1, 2, 100500
ищем 100400
какой будет индекс?

2022-04-27 14:40 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +	}
получили результаты, например 1, 20, 55
ищем каждый из них в индексе
так обычно и происходит

2022-05-01 08:00 UTC, DmitriyVTitov approved these changes
Замечания не учтены.

2022-05-01 08:00 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +		// binary search in index slice
комментарии не привносят ценности

2022-05-01 08:00 UTC, DmitriyVTitov commented on hw3/cmd/main/main.go
> +}
то есть для КАЖДОГО документа из всего массива просканированных ищется ID в массиве результатов поиска
я уже не раз про это писал, но изменений нет

представьте, что Яндекс так делал бы для всех триллионов проиндексированных документов, работало бы?

2022-05-01 21:59 UTC, merged